server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用微服务名称j进行路由
      routes:
        - id: payment_route # 路由的id,没有规定规则但要求唯一,建议配合服务名
#          uri: http://localhost:8001 #匹配后提供服务的路由的地址
#          lb://serviceName是spring cloud中gateway在微服务中自动为我们创建的负载均衡uri
          uri: lb://cloud-payment-service #匹配后提供服务的路由的地址，uri的协议为b，表示启用Gateway的负载均衡功能，
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的进行路由

        - id: payment_route2
#          uri: http://localhost:8001l
          uri: lb://cloud-payment-service
#           过滤
#          filters:
#            - AddRequestHeader=X-Request-Id, 1024 #过滤器工厂会在匹配的请求头加上一对请求头，名称为X-Request-Id值为1024
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
#            - Before=2017-01-20T17:42:47.789-07:00[America/Denver]
#            - Between=2017-01-20T17:42:47.789-07:00[America/Denver],2020-07-06T20:47:57.416+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy #http://localhost:9527/payment/lb --cookie "username=zzyy" 才能访问成功
#            - Header=X-Request-Id, \d+ #请求头要有X-Request-Id属性，并且值为正数  例如：http://localhost:9527/payment/lb -H "X-Request-ld: 123"才能访问成功
#            - Host=**.atguigu.com #http://localhost:9527/payment/lb -H "Host:news.atguigu.com" 才能访问成功
#            - Method=GET
#            - Query=username, \d+ # 要有参数名username并且值还要是正整数才能路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/